server:
  port: 8080
spring:
  application:
    name: nw
  datasource:
    username: root
    password: 123456
    url=: jdbc:mysql://localhost:3306/crawler?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver


